name = "ArraysExtra"
uuid = "38052440-ad76-4236-8414-61389b2c5143"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
StructArrays = "0.6.12"
julia = "1.6"
